name: build and release

on: [push]    

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write    

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install packages & setup
        run: |
          sudo apt update -y   
          sudo apt install libncurses5-dev python2 libtinfo5 -y      
          bash init_clang_13.sh
          
      - name: Set environment variable
        run: |
          echo "LPOS_KERNEL_VERSION=${{ github.event.inputs.tag }}" >> $GITHUB_ENV
          
      - name: Building LPoS
        run: |
          export PATH=$HOME/:$PWD/toolchain/bin:$PATH
          bash build.sh -c

      - name: Building LPoS + KernelSU
        run: |
          export PATH=$HOME/:$PWD/toolchain/bin:$PATH
          bash build.sh -k          

      - name: Upload kernel
        uses: actions/upload-artifact@v4
        with:
          name: "LPoS-${{ env.LPOS_KERNEL_VERSION }}-[S10+]"
          path: |
            out/LPoS*.zip
            out/KSU*.zip
